name: SSD Hyperscale Automation Framework By Bang Thien Nguyen
# push to main
# Whenever you commit and push code to the main branch, the workflow runs automatically.
# pull_request to main
# Whenever someone opens a pull request targeting the main branch, the workflow runs to check the code before merging.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Runs at 1:00 AM PT every day.
    - cron: '0 8 * * *'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave-html-pretty-formatter

      - name: Run Behave Tests
        run: |
          mkdir -p reports
          behave --tags=@adv --exclude "features/manual_tests" --format behave_html_pretty_formatter:PrettyHTMLFormatter -o index.html
    
      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-report-${{ matrix.os }}
          # The path is now simply 'index.html' from the root of the repo
          path: index.html

      - name: Deploy Report to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Publish from the root directory of the repo
          publish_dir: .
          publish_branch: gh-pages
          keep_files: true
